apiVersion: v1
kind: Service
metadata:
  name: linear-regression-service
spec:
  type: NodePort
  selector:
    app: linear-regression
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30001
